<a href="https://colab.research.google.com/github/AlexNedyalkov/Washington-University-Application-Neural-Networks/blob/master/Applications_of_DNNs_Assignment_AlexNedyalkov_class2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a href="https://colab.research.google.com/github/jeffheaton/t81_558_deep_learning/blob/master/assignments/assignment_yourname_class2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# T81-558: Applications of Deep Neural Networks
* Instructor: [Jeff Heaton](https://sites.wustl.edu/jeffheaton/), School of Engineering and Applied Science, [Washington University in St. Louis](https://engineering.wustl.edu/Programs/Pages/default.aspx)
* For more information visit the [class website](https://sites.wustl.edu/jeffheaton/t81-558/).

**Module 2 Assignment: Creating Columns in Pandas**

**Student Name: Alex Nedyalkov**

# Assignment Instructions

For this assignment, you will use the **reg-33-data.csv** dataset.  This file contains a dataset that I generated specifically for this class.  You can find the CSV file on my data site, at this location: [reg-33-data.csv](http://data.heatonresearch.com/data/t81-558/datasets/reg-33-data.csv).

For this assignment, load and modify the data set.  You will submit this modified dataset to the **submit** function.  See [Assignment #1](https://github.com/jeffheaton/t81_558_deep_learning/blob/master/assignments/assignment_yourname_class1.ipynb) for details on how to submit an assignment or check that one was submitted.

Modify the dataset as follows:

* Add a column named *ratio* that is *max* divided by *number*.  Leave *max* and *number* in the dataframe.
* Replace the *cat2* column with dummy variables. e.g. 'cat2_CA-0', 'cat2_CA-1',
       'cat2_CA-10', 'cat2_CA-11', 'cat2_CA-12', ...
* Replace the *item* column with dummy variables, e.g. 'item_IT-0', 'item_IT-1',
       'item_IT-10', 'item_IT-11', 'item_IT-12', ...
* For field *length* replace missing values with the median of *length*.
* For field *height* replace missing with median and convert to zscore.
* Remove all other columns.
* Your submitted dataframe will have these columns: 'height', 'max', 'number', 'length', 'ratio', 'cat2_CA-0', 'cat2_CA-1',
       'cat2_CA-10', 'cat2_CA-11', 'cat2_CA-12', 'cat2_CA-13', 'cat2_CA-14',
       'cat2_CA-15', 'cat2_CA-16', 'cat2_CA-17', 'cat2_CA-18', 'cat2_CA-19',
       'cat2_CA-1A', 'cat2_CA-1B', 'cat2_CA-1C', 'cat2_CA-1D', 'cat2_CA-1E',
       'cat2_CA-1F', 'cat2_CA-2', 'cat2_CA-20', 'cat2_CA-21', 'cat2_CA-22',
       'cat2_CA-23', 'cat2_CA-24', 'cat2_CA-25', 'cat2_CA-26', 'cat2_CA-27',
       'cat2_CA-3', 'cat2_CA-4', 'cat2_CA-5', 'cat2_CA-6', 'cat2_CA-7',
       'cat2_CA-8', 'cat2_CA-9', 'cat2_CA-A', 'cat2_CA-B', 'cat2_CA-C',
       'cat2_CA-D', 'cat2_CA-E', 'cat2_CA-F', 'item_IT-0', 'item_IT-1',
       'item_IT-10', 'item_IT-11', 'item_IT-12', 'item_IT-13', 'item_IT-14',
       'item_IT-15', 'item_IT-16', 'item_IT-17', 'item_IT-18', 'item_IT-19',
       'item_IT-1A', 'item_IT-1B', 'item_IT-1C', 'item_IT-1D', 'item_IT-1E',
       'item_IT-2', 'item_IT-3', 'item_IT-4', 'item_IT-5', 'item_IT-6',
       'item_IT-7', 'item_IT-8', 'item_IT-9', 'item_IT-A', 'item_IT-B',
       'item_IT-C', 'item_IT-D', 'item_IT-E', 'item_IT-F'.

# Google CoLab Instructions

If you are using Google CoLab, it will be necessary to mount your GDrive so that you can send your notebook during the submit process. Running the following code will map your GDrive to ```/content/drive```.

In [1]:
try:
    from google.colab import drive
    drive.mount('/content/drive', force_remount=True)
    COLAB = True
    print("Note: using Google CoLab")
    %tensorflow_version 2.x
except:
    print("Note: not using Google CoLab")
    COLAB = False

Mounted at /content/drive
Note: using Google CoLab
TensorFlow 2.x selected.

# Assignment Submit Function

You will submit the ten programming assignments electronically.  The following **submit** function can be used to do this.  My server will perform a basic check of each assignment and let you know if it sees any underlying problems. 

**It is unlikely that should need to modify this function.**

In [0]:
import base64
import os
import numpy as np
import pandas as pd
import requests

# This function submits an assignment.  You can submit an assignment as much as you like, only the final
# submission counts.  The paramaters are as follows:
# data - Pandas dataframe output.
# key - Your student key that was emailed to you.
# no - The assignment class number, should be 1 through 1.
# source_file - The full path to your Python or IPYNB file.  This must have "_class1" as part of its name.  
# .             The number must match your assignment number.  For example "_class2" for class assignment #2.
def submit(data,key,no,source_file=None):
    if source_file is None and '__file__' not in globals(): raise Exception('Must specify a filename when a Jupyter notebook.')
    if source_file is None: source_file = __file__
    suffix = '_class{}'.format(no)
    if suffix not in source_file: raise Exception('{} must be part of the filename.'.format(suffix))
    with open(source_file, "rb") as image_file:
        encoded_python = base64.b64encode(image_file.read()).decode('ascii')
    ext = os.path.splitext(source_file)[-1].lower()
    if ext not in ['.ipynb','.py']: raise Exception("Source file is {} must be .py or .ipynb".format(ext))
    r = requests.post("https://api.heatonresearch.com/assignment-submit",
        headers={'x-api-key':key}, json={'csv':base64.b64encode(data.to_csv(index=False).encode('ascii')).decode("ascii"),
        'assignment': no, 'ext':ext, 'py':encoded_python})
    if r.status_code == 200:
        print("Success: {}".format(r.text))
    else: print("Failure: {}".format(r.text))

# Assignment #2 Sample Code

The following code provides a starting point for this assignment.

In [3]:
import os
import pandas as pd
from scipy.stats import zscore

# This is your student key that I emailed to you at the beginnning of the semester.
key = "4ELU3949Wc96YNTZAOW9s2dWbOmBHgQ2a5x9EqEh"  # This is an example key and will not work.

# You must also identify your source file.  (modify for your local setup)
# file='/content/drive/My Drive/Colab Notebooks/assignment_yourname_class2.ipynb'  # Google CoLab
# file='C:\\Users\\jeffh\\projects\\t81_558_deep_learning\\assignments\\assignment_yourname_class2.ipynb'  # Windows
file='/content/drive/My Drive/Colab Notebooks/Washinton_University_Applications_Deep_Neural_Networks/Assignments/Applications_of_DNNs_Assignment_AlexNedyalkov_class2.ipynb'  # Mac/Linux

# Begin assignment
df = pd.read_csv("http://data.heatonresearch.com/data/t81-558/datasets/reg-33-data.csv")

df.drop('id',1,inplace=True)

display(df[:10])

  convention   height    max   cat2  ...   item weight country         target
0      CO-1A  4284.51  44907   CA-E  ...  IT-17  13722    CO-1   44098.106769
1       CO-C   806.88  48831   CA-A  ...  IT-1E  33779    CO-0   95567.294044
2      CO-19  2859.80  40760  CA-16  ...  IT-14  26633   CO-23   48583.507153
3      CO-2B  5823.87  33597   CA-9  ...   IT-8  14537   CO-11  130572.202064
4       CO-5      NaN  29848   CA-9  ...   IT-5  21135   CO-1E   85768.812850
5       CO-4  2030.39  46624  CA-17  ...   IT-F  51085    CO-D   75530.979003
6      CO-19  6804.32  41022  CA-1F  ...   IT-B  47594   CO-16   34056.254651
7       CO-A      NaN  32791  CA-22  ...   IT-E  20528   CO-1A   87353.121755
8       CO-E  5865.44  64563   CA-9  ...   IT-A  40902   CO-16   67926.242813
9       CO-9  5615.70  50865  CA-18  ...  IT-1B   2762    CO-9  134219.585619

[10 rows x 14 columns]

In [0]:
df["ratio"] = df["max"] / df["number"]

In [0]:
dummies_cat = pd.get_dummies(df["cat2"],drop_first=False, prefix = "cat2")
df = pd.concat((df, dummies_cat), axis = 1)
df.drop(labels = "cat2", axis = 1, inplace = True)

In [0]:
dummies_item = pd.get_dummies(df["item"], prefix = "item")
df = pd.concat((df, dummies_item), axis = 1)
df.drop(labels = "item", axis = 1, inplace = True)

In [7]:
med_length = df.length.median()
med_length
df.length.fillna(med_length, inplace = True,)
print(df.length.mean())
df.length.isna().sum()

13511.39790573128

0

In [8]:
med_height = df.height.median()
df.height.fillna(med_height, inplace = True)
print(df.height.mean())
df.height = zscore(df.height)
print(df.height.mean())

3470.135370524681
4.9240532704718295e-17

In [0]:
#For field length replace missing values with the median of length.
med_length = df.length.median()
df.length.fillna(med_length, inplace = True)
#For field height replace missing with median and convert to zscore.
med_height = df.height.median()
df.height.fillna(med_height, inplace = True)
df.height = zscore(df.height)

In [10]:
display(df[0:5])

  convention    height    max  ...  item_IT-D item_IT-E item_IT-F
0      CO-1A  0.453222  44907  ...          0         0         0
1       CO-C -1.482176  48831  ...          0         0         0
2      CO-19 -0.339669  40760  ...          0         0         0
3      CO-2B  1.309919  33597  ...          0         0         0
4       CO-5  0.006937  29848  ...          0         0         0

[5 rows x 84 columns]

In [0]:
df.drop(labels = ["convention", "usage", "region", "code", "power", "weight", "country", "target"], axis = 1, inplace = True)

In [12]:
df

         height    max  number  ...  item_IT-D  item_IT-E  item_IT-F
0      0.453222  44907   16669  ...          0          0          0
1     -1.482176  48831    8652  ...          0          0          0
2     -0.339669  40760   23103  ...          0          0          0
3      1.309919  33597   17680  ...          0          0          0
4      0.006937  29848   24136  ...          0          0          0
...         ...    ...     ...  ...        ...        ...        ...
10804 -0.872850  49087   10679  ...          0          0          0
10805  1.611212  37253   19960  ...          0          0          0
10806  1.362800  30925   27776  ...          0          0          0
10807 -1.651243  47998   25741  ...          0          1          0
10808  1.514309  29149   19425  ...          0          0          0

[10809 rows x 76 columns]

In [13]:

# Submit assignment
submit(source_file=file,data=df,key=key,no=2)

Success: Submitted Assignment 2 for alexander-nedyalkov:
You have submitted this assignment 5 times. (this is fine)
No warnings on your data. You will probably do well, but no guarantee. :-)